/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponsesAddressRunesBalanceListItem struct {
	Amount string `json:"amount,omitempty"`
	ParsedAmount string `json:"parsedAmount,omitempty"`
	RuneId string `json:"rune_id,omitempty"`
	SpacedRune string `json:"spacedRune,omitempty"`
}
