/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliEstimateRawFee struct {
	// Estimate for long time horizon
	Long *AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeLong `json:"long,omitempty"`
	// Estimate for medium time horizon
	Medium *AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeMedium `json:"medium,omitempty"`
	// Estimate for short time horizon
	Short *AllOfgithubComSatstreamSsUtilsBitcoinCliEstimateRawFeeShort `json:"short,omitempty"`
}
