/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponsesNonInscriptionUtxo struct {
	Address string `json:"address,omitempty"`
	CodeType int32 `json:"codeType,omitempty"`
	Height int32 `json:"height,omitempty"`
	Idx int32 `json:"idx,omitempty"`
	IsOpInRBF bool `json:"isOpInRBF,omitempty"`
	IsSpent bool `json:"isSpent,omitempty"`
	Satoshi *BigInt `json:"satoshi,omitempty"`
	ScriptPk string `json:"scriptPk,omitempty"`
	ScriptType string `json:"scriptType,omitempty"`
	Txid string `json:"txid,omitempty"`
	Vout int32 `json:"vout,omitempty"`
}
