/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsOrdServerResponsesRuneDetails struct {
	Amount int32 `json:"amount,omitempty"`
	Divisibility int32 `json:"divisibility,omitempty"`
	Symbol string `json:"symbol,omitempty"`
}
