/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type RequestsDecodeScriptRequest struct {
	// The hex-encoded script to decode
	Hexstring string `json:"hexstring"`
}
