/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type UtxoBlockInfo struct {
	// Coinbase subsidy amount of this block
	Coinbase float64 `json:"coinbase,omitempty"`
	// Total amount of new outputs created by this block
	NewOutputsExCoinbase float64 `json:"new_outputs_ex_coinbase,omitempty"`
	// Total amount of all prevouts spent in this block
	PrevoutSpent float64 `json:"prevout_spent,omitempty"`
	// Total amount of unspendable outputs created
	Unspendable float64 `json:"unspendable,omitempty"`
	// Detailed view of unspendable categories
	Unspendables *AllOfUtxoBlockInfoUnspendables `json:"unspendables,omitempty"`
}
