/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsOrdServerResponsesRuneResponse struct {
	Entry *GithubComSatstreamSsUtilsOrdServerResponsesRuneEntry `json:"entry,omitempty"`
	Id string `json:"id,omitempty"`
	Mintable bool `json:"mintable,omitempty"`
	Parent string `json:"parent,omitempty"`
}
