/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type TransactionVerifyTxOutProofRequest struct {
	// The hex-encoded proof generated by gettxoutproof
	Proof string `json:"proof,omitempty"`
}
