/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type RunesBalance struct {
	Amount string `json:"amount,omitempty"`
	SpacedRune string `json:"spaced_rune,omitempty"`
	Symbol string `json:"symbol,omitempty"`
}
