/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type SatoshiResponse struct {
	Block int32 `json:"block,omitempty"`
	Charms []string `json:"charms,omitempty"`
	Cycle int32 `json:"cycle,omitempty"`
	Decimal string `json:"decimal,omitempty"`
	Degree string `json:"degree,omitempty"`
	Epoch int32 `json:"epoch,omitempty"`
	Inscriptions []string `json:"inscriptions,omitempty"`
	Name string `json:"name,omitempty"`
	Number int32 `json:"number,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Percentile string `json:"percentile,omitempty"`
	Period int32 `json:"period,omitempty"`
	Rarity string `json:"rarity,omitempty"`
	Satpoint string `json:"satpoint,omitempty"`
	Timestamp int32 `json:"timestamp,omitempty"`
}
