/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type UnknownFields struct {
	// Map of unknown field names to their values
	Fields map[string]string `json:"fields,omitempty"`
}
