/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type CreatePsbtRequest struct {
	// The inputs for the transaction
	Inputs []CreatePsbtInput `json:"inputs"`
	// Raw locktime. Non-0 value also locktime-activates inputs
	Locktime int32 `json:"locktime,omitempty"`
	// The outputs (address:amount pairs or {\"data\":\"hex\"})
	Outputs []CreatePsbtOutput `json:"outputs"`
	// Marks this transaction as BIP125-replaceable
	Replaceable bool `json:"replaceable,omitempty"`
}
