/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TypesApiKey struct {
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	RateLimitMax int32 `json:"rate_limit_max,omitempty"`
	RateLimitWindowSecs int32 `json:"rate_limit_window_secs,omitempty"`
	Revoked bool `json:"revoked,omitempty"`
	Subscription *TypesSubscription `json:"subscription,omitempty"`
	// * SubscriptionID is used to check for revoked and expired subscriptions
	SubscriptionId string `json:"subscription_id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
