/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type Transaction struct {
	Input []Input `json:"input,omitempty"`
	LockTime int32 `json:"lock_time,omitempty"`
	Output []Output `json:"output,omitempty"`
	Version int32 `json:"version,omitempty"`
}
