/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliDecodedPsbt struct {
	// The transaction fee paid if all UTXOs slots are filled
	Fee float64 `json:"fee,omitempty"`
	// Array of inputs
	Inputs []GithubComSatstreamSsUtilsBitcoinCliDecodedPsbtInput `json:"inputs,omitempty"`
	// Array of outputs
	Outputs []GithubComSatstreamSsUtilsBitcoinCliDecodedPsbtOutput `json:"outputs,omitempty"`
	// The decoded network-serialized unsigned transaction
	Tx *AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPsbttx `json:"tx,omitempty"`
	// The unknown global fields
	Unknown ModelMap `json:"unknown,omitempty"`
}
