/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// Fee estimation data
type AllOfresponsesEstimateRawFeeResponseData struct {
	// Estimate for long time horizon
	Long *interface{} `json:"long,omitempty"`
	// Estimate for medium time horizon
	Medium *interface{} `json:"medium,omitempty"`
	// Estimate for short time horizon
	Short *interface{} `json:"short,omitempty"`
}
