/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsOrdServerResponsesRuneListEntry struct {
	// The first element is the ID
	Var0 string `json:"0,omitempty"`
	// The second element is the entry data
	Var1 *AllOfgithubComSatstreamSsUtilsOrdServerResponsesRuneListEntryVar1 `json:"1,omitempty"`
}
