/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream-go-sdk

type ResponsesGetRunesInfoListData struct {
	Pagination *ResponsesPaginationInfo `json:"pagination,omitempty"`
	Runes []ResponsesRuneInfo `json:"runes,omitempty"`
}
