/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type TestMempoolFees struct {
	// Transaction fee in BTC
	Base float64 `json:"base,omitempty"`
}
