/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliUtxoSetInfo struct {
	// The hash of the block at which these statistics are calculated
	Bestblock string `json:"bestblock,omitempty"`
	// Info on amounts in the block at this height
	BlockInfo *AllOfgithubComSatstreamSsUtilsBitcoinCliUtxoSetInfoBlockInfo `json:"block_info,omitempty"`
	// Database-independent metric indicating the UTXO set size
	Bogosize int32 `json:"bogosize,omitempty"`
	// The estimated size of the chainstate on disk
	DiskSize int32 `json:"disk_size,omitempty"`
	// The serialized hash (only for hash_serialized_2)
	HashSerialized2 string `json:"hash_serialized_2,omitempty"`
	// The block height of the returned statistics
	Height int32 `json:"height,omitempty"`
	// The serialized hash (only for muhash)
	Muhash string `json:"muhash,omitempty"`
	// The total amount of coins in the UTXO set
	TotalAmount float64 `json:"total_amount,omitempty"`
	// Total amount permanently excluded from UTXO set
	TotalUnspendableAmount float64 `json:"total_unspendable_amount,omitempty"`
	// The number of transactions with unspent outputs
	Transactions int32 `json:"transactions,omitempty"`
	// The number of unspent transaction outputs
	Txouts int32 `json:"txouts,omitempty"`
}
