/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2007 struct {
	BlocksBase *BlocksBase `json:"blocks.Base,omitempty"`
	Data *GithubComSatstreamSsUtilsRpcBtcTx `json:"data,omitempty"`
}
