/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type BlockVin2 struct {
	// Coinbase transaction input
	Coinbase string `json:"coinbase,omitempty"`
	// The script signature
	ScriptSig *AllOfBlockVin2ScriptSig `json:"scriptSig,omitempty"`
	// Input sequence number
	Sequence int32 `json:"sequence,omitempty"`
	// Transaction ID of the referenced output
	Txid string `json:"txid,omitempty"`
	Txinwitness []string `json:"txinwitness,omitempty"`
	// Index of the referenced output
	Vout int32 `json:"vout,omitempty"`
}
