/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliChainTxStats struct {
	// The timestamp for the final block in the window
	Time int32 `json:"time,omitempty"`
	// The total number of transactions in the chain
	Txcount int32 `json:"txcount,omitempty"`
	// The average rate of transactions per second
	Txrate float64 `json:"txrate,omitempty"`
	// Size of the window in number of blocks
	WindowBlockCount int32 `json:"window_block_count,omitempty"`
	// The hash of the final block in the window
	WindowFinalBlockHash string `json:"window_final_block_hash,omitempty"`
	// The height of the final block in the window
	WindowFinalBlockHeight int32 `json:"window_final_block_height,omitempty"`
	// The elapsed time in the window in seconds
	WindowInterval int32 `json:"window_interval,omitempty"`
	// The number of transactions in the window
	WindowTxCount int32 `json:"window_tx_count,omitempty"`
}
