/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliPsbtBip32Deriv struct {
	// The fingerprint of the master key
	MasterFingerprint string `json:"master_fingerprint,omitempty"`
	// The derivation path
	Path string `json:"path,omitempty"`
	// The public key
	Pubkey string `json:"pubkey,omitempty"`
}
