/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type MempoolInfo struct {
	// Sum of all virtual transaction sizes
	Bytes int32 `json:"bytes,omitempty"`
	// True if mempool accepts RBF without signaling inspection
	Fullrbf bool `json:"fullrbf,omitempty"`
	// Minimum fee rate increment for mempool limiting
	Incrementalrelayfee float64 `json:"incrementalrelayfee,omitempty"`
	// True if the mempool is fully loaded
	Loaded bool `json:"loaded,omitempty"`
	// Maximum memory usage for the mempool
	Maxmempool int32 `json:"maxmempool,omitempty"`
	// Minimum fee rate in BTC/kvB for tx to be accepted
	Mempoolminfee float64 `json:"mempoolminfee,omitempty"`
	// Current minimum relay fee for transactions
	Minrelaytxfee float64 `json:"minrelaytxfee,omitempty"`
	// Current tx count
	Size int32 `json:"size,omitempty"`
	// Total fees for the mempool in BTC
	TotalFee float64 `json:"total_fee,omitempty"`
	// Number of unbroadcast transactions
	Unbroadcastcount int32 `json:"unbroadcastcount,omitempty"`
	// Total memory usage for the mempool
	Usage int32 `json:"usage,omitempty"`
}
