/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TypesSubscriptionType string

// List of types.SubscriptionType
const (
	FREE_TypesSubscriptionType TypesSubscriptionType = "free"
	TIER1_TypesSubscriptionType TypesSubscriptionType = "tier1"
	TIER2_TypesSubscriptionType TypesSubscriptionType = "tier2"
	TIER3_TypesSubscriptionType TypesSubscriptionType = "tier3"
)
