/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2005 struct {
	Data *GithubComSatstreamSsUtilsRpcBlock `json:"data,omitempty"`
	ResponsesBase *ResponsesBase `json:"responses.Base,omitempty"`
}
