/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type RawMempoolData struct {
	// Only if verbose is true
	Detailed map[string]MempoolEntry `json:"detailed,omitempty"`
	// Only if mempool_sequence is true
	Sequence *AllOfRawMempoolDataSequence `json:"sequence,omitempty"`
	// Only if verbose is false
	Txids []string `json:"txids,omitempty"`
}
