/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TypesUserApp struct {
	ApiKey *TypesApiKey `json:"api_key,omitempty"`
	ApiKeyId string `json:"api_key_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Subscription *TypesSubscription `json:"subscription,omitempty"`
	SubscriptionId string `json:"subscription_id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
