/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type MiningInfo struct {
	// The current block
	Blocks int32 `json:"blocks,omitempty"`
	// Current network name
	Chain string `json:"chain,omitempty"`
	// The number of block transactions of the last assembled block
	Currentblocktx int32 `json:"currentblocktx,omitempty"`
	// The block weight of the last assembled block
	Currentblockweight int32 `json:"currentblockweight,omitempty"`
	// The current difficulty
	Difficulty float64 `json:"difficulty,omitempty"`
	// The network hashes per second
	Networkhashps float64 `json:"networkhashps,omitempty"`
	// The size of the mempool
	Pooledtx int32 `json:"pooledtx,omitempty"`
	// Any network and blockchain warnings
	Warnings string `json:"warnings,omitempty"`
}
