/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsOrdServerResponsesTransactionOutput struct {
	ScriptPubkey string `json:"script_pubkey,omitempty"`
	Value int32 `json:"value,omitempty"`
}
