/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliBlock2 struct {
	Bits string `json:"bits,omitempty"`
	Chainwork string `json:"chainwork,omitempty"`
	Confirmations int32 `json:"confirmations,omitempty"`
	Difficulty float64 `json:"difficulty,omitempty"`
	Hash string `json:"hash,omitempty"`
	Height int32 `json:"height,omitempty"`
	Mediantime int32 `json:"mediantime,omitempty"`
	Merkleroot string `json:"merkleroot,omitempty"`
	NTx int32 `json:"nTx,omitempty"`
	Nextblockhash string `json:"nextblockhash,omitempty"`
	Nonce int32 `json:"nonce,omitempty"`
	Previousblockhash string `json:"previousblockhash,omitempty"`
	Size int32 `json:"size,omitempty"`
	Strippedsize int32 `json:"strippedsize,omitempty"`
	Time int32 `json:"time,omitempty"`
	// List of detailed transactions
	Tx []GithubComSatstreamSsUtilsBitcoinCliBtcTx2 `json:"tx,omitempty"`
	Version int32 `json:"version,omitempty"`
	VersionHex string `json:"versionHex,omitempty"`
	Weight int32 `json:"weight,omitempty"`
}
