/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type Duration struct {
	Nanos int32 `json:"nanos,omitempty"`
	Secs int32 `json:"secs,omitempty"`
}
