/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResponsesAddressNonInscriptionUtxoData struct {
	Cursor int32 `json:"cursor,omitempty"`
	Total int32 `json:"total,omitempty"`
	TotalConfirmed int32 `json:"totalConfirmed,omitempty"`
	TotalRunes int32 `json:"totalRunes,omitempty"`
	TotalUnconfirmed int32 `json:"totalUnconfirmed,omitempty"`
	TotalUnconfirmedSpend int32 `json:"totalUnconfirmedSpend,omitempty"`
	Utxo []ResponsesNonInscriptionUtxo `json:"utxo,omitempty"`
}
