/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// Witness script details
type AllOfDecodedScriptSegwit struct {
	// The Bitcoin address (only if well-defined)
	Address string `json:"address,omitempty"`
	// String representation of the script public key
	Asm string `json:"asm,omitempty"`
	// Inferred descriptor for the script
	Desc string `json:"desc,omitempty"`
	// Hex string of the script public key
	Hex string `json:"hex,omitempty"`
	// P2SH address wrapping this witness script
	P2shSegwit string `json:"p2sh-segwit,omitempty"`
	// The type of the script public key
	Type_ string `json:"type,omitempty"`
}
