/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GithubComSatstreamSsUtilsRpcScriptPubKey struct {
	Address string `json:"address,omitempty"`
	Asm string `json:"asm,omitempty"`
	Desc string `json:"desc,omitempty"`
	Hex string `json:"hex,omitempty"`
	Type_ string `json:"type,omitempty"`
}
