/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type MempoolEntry struct {
	// Number of in-mempool ancestor transactions
	Ancestorcount int32 `json:"ancestorcount,omitempty"`
	// Virtual size of in-mempool ancestors
	Ancestorsize int32 `json:"ancestorsize,omitempty"`
	// Whether this transaction is replaceable
	Bip125Replaceable bool `json:"bip125-replaceable,omitempty"`
	// Parent transaction IDs
	Depends []string `json:"depends,omitempty"`
	// Number of in-mempool descendant transactions
	Descendantcount int32 `json:"descendantcount,omitempty"`
	// Virtual size of in-mempool descendants
	Descendantsize int32 `json:"descendantsize,omitempty"`
	// Fee information
	Fees *AllOfMempoolEntryFees `json:"fees,omitempty"`
	// Block height when transaction entered pool
	Height int32 `json:"height,omitempty"`
	// Child transaction IDs
	Spentby []string `json:"spentby,omitempty"`
	// Time transaction entered pool
	Time int32 `json:"time,omitempty"`
	// Whether this transaction is currently unbroadcast
	Unbroadcast bool `json:"unbroadcast,omitempty"`
	// Virtual transaction size
	Vsize int32 `json:"vsize,omitempty"`
	// Transaction weight
	Weight int32 `json:"weight,omitempty"`
	// Hash of serialized transaction with witness data
	Wtxid string `json:"wtxid,omitempty"`
}
