/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResponsesRuneInfo struct {
	BlockHeight int32 `json:"block_height,omitempty"`
	Divisibility int32 `json:"divisibility,omitempty"`
	Minted string `json:"minted,omitempty"`
	Premine *BigInt `json:"premine,omitempty"`
	Rune_ string `json:"rune,omitempty"`
	RuneId string `json:"rune_id,omitempty"`
	SpacedRune string `json:"spaced_rune,omitempty"`
	Spacers int32 `json:"spacers,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Terms *GithubComSatstreamSsUtilsOrdinalsTerms `json:"terms,omitempty"`
	Turbo bool `json:"turbo,omitempty"`
	TxHeight int32 `json:"tx_height,omitempty"`
	Txid string `json:"txid,omitempty"`
}
