/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput struct {
	// The transaction id
	Txid string `json:"txid,omitempty"`
	// The output number
	Vout int32 `json:"vout,omitempty"`
}
