/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// The witness script
type AllOfDecodedPsbtOutputWitnessScript struct {
	// The Bitcoin address (if there is one)
	Address string `json:"address,omitempty"`
	// The assembly representation of the script
	Asm string `json:"asm,omitempty"`
	// The hex representation of the script
	Hex string `json:"hex,omitempty"`
	// The type of the script (e.g., 'pubkeyhash')
	Type_ string `json:"type,omitempty"`
}
