/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GetRawMempoolRequest struct {
	// Optional: Returns txids with mempool sequence number
	MempoolSequence bool `json:"mempool_sequence,omitempty"`
}
