/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliPsbtMissingData struct {
	Pubkeys []string `json:"pubkeys,omitempty"`
	Redeemscript string `json:"redeemscript,omitempty"`
	Signatures []string `json:"signatures,omitempty"`
	Witnessscript string `json:"witnessscript,omitempty"`
}
