/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsApiServerApiPsbtRequestsCreatePsbtOutput struct {
	Address string `json:"address,omitempty"`
	Data string `json:"data,omitempty"`
}
