/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse2002 struct {
	Data []ResponsesGetAddressRunesBalanceListItem `json:"data,omitempty"`
	GithubComSatstreamSsApiServerApiAddressesResponsesBaseResponse *GithubComSatstreamSsApiServerApiAddressesResponsesBaseResponse `json:"github_com_satstream_ss-api_server_api_addresses_responses.BaseResponse,omitempty"`
}
