/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliDecodedPsbtOutput struct {
	// The BIP32 derivation paths
	Bip32Derivs []GithubComSatstreamSsUtilsBitcoinCliPsbtBip32Deriv `json:"bip32_derivs,omitempty"`
	// The redeem script
	RedeemScript *AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPsbtOutputRedeemScript `json:"redeem_script,omitempty"`
	// Unknown fields
	Unknown ModelMap `json:"unknown,omitempty"`
	// The witness script
	WitnessScript *AllOfgithubComSatstreamSsUtilsBitcoinCliDecodedPsbtOutputWitnessScript `json:"witness_script,omitempty"`
}
