/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// Information about lowest range of feerates to succeed
type AllOfFeeHorizonEstimatePass struct {
	// End of feerate range
	Endrange float64 `json:"endrange,omitempty"`
	// Current number of txs in mempool unconfirmed
	Inmempool float64 `json:"inmempool,omitempty"`
	// Number of txs that left mempool unconfirmed
	Leftmempool float64 `json:"leftmempool,omitempty"`
	// Start of feerate range
	Startrange float64 `json:"startrange,omitempty"`
	// Total number of txs confirmed
	Totalconfirmed float64 `json:"totalconfirmed,omitempty"`
	// Number of txs confirmed within target
	Withintarget float64 `json:"withintarget,omitempty"`
}
