/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsDatabaseAddressDelta struct {
	Address string `json:"address,omitempty"`
	Amount int32 `json:"amount,omitempty"`
	BlockHeight int32 `json:"block_height,omitempty"`
}
