/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type PsbtAnalysis struct {
	Error_ string `json:"error,omitempty"`
	EstimatedFeerate float64 `json:"estimated_feerate,omitempty"`
	EstimatedVsize int32 `json:"estimated_vsize,omitempty"`
	Fee float64 `json:"fee,omitempty"`
	Inputs []PsbtInputAnalysis `json:"inputs,omitempty"`
	Next string `json:"next,omitempty"`
}
