/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type RequestsGetTxOutSetInfoRequest struct {
	// Block hash or height
	HashOrHeight *interface{} `json:"hash_or_height,omitempty"`
	// Which UTXO set hash should be calculated
	HashType string `json:"hash_type,omitempty"`
	// Whether to use coinstatsindex
	UseIndex bool `json:"use_index,omitempty"`
}
