/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type DecodedPsbtOutput struct {
	// The BIP32 derivation paths
	Bip32Derivs []PsbtBip32Deriv `json:"bip32_derivs,omitempty"`
	// The redeem script
	RedeemScript *AllOfDecodedPsbtOutputRedeemScript `json:"redeem_script,omitempty"`
	// Unknown fields
	Unknown *AllOfDecodedPsbtOutputUnknown `json:"unknown,omitempty"`
	// The witness script
	WitnessScript *AllOfDecodedPsbtOutputWitnessScript `json:"witness_script,omitempty"`
}
