/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// Transaction output details (null if not found)
type AllOfresponsesGetTxOutResponseData struct {
	// The hash of the block at the tip of the chain
	Bestblock string `json:"bestblock,omitempty"`
	// Whether this is a coinbase transaction
	Coinbase bool `json:"coinbase,omitempty"`
	// The number of confirmations
	Confirmations int32 `json:"confirmations,omitempty"`
	// The public key script
	ScriptPubKey *interface{} `json:"scriptPubKey,omitempty"`
	// The transaction value in BTC
	Value float64 `json:"value,omitempty"`
}
