/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream-go-sdk

type ResponsesGetRuneHoldersData struct {
	Holders []ResponsesRuneHolder `json:"holders,omitempty"`
	Pagination *ResponsesPaginationInfo `json:"pagination,omitempty"`
}
