/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type Input struct {
	PreviousOutput string `json:"previous_output,omitempty"`
	ScriptSig string `json:"script_sig,omitempty"`
	Sequence int32 `json:"sequence,omitempty"`
	Witness []string `json:"witness,omitempty"`
}
