/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsApiServerApiPsbtRequestsCreatePsbtRequest struct {
	Inputs []GithubComSatstreamSsApiServerApiPsbtRequestsCreatePsbtInput `json:"inputs"`
	Locktime int32 `json:"locktime,omitempty"`
	Outputs []GithubComSatstreamSsApiServerApiPsbtRequestsCreatePsbtOutput `json:"outputs"`
	Replaceable bool `json:"replaceable,omitempty"`
}
