/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

// Time       time.Time  `json:\"time\"`
type AllOfresponsesGetAddressTimeframeBalanceItemBlockRange struct {
	End int32 `json:"end,omitempty"`
	Start int32 `json:"start,omitempty"`
}
