/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsOrdServerResponsesStatusResponse struct {
	AddressIndex bool `json:"address_index,omitempty"`
	BlessedInscriptions int32 `json:"blessed_inscriptions,omitempty"`
	Chain string `json:"chain,omitempty"`
	CursedInscriptions int32 `json:"cursed_inscriptions,omitempty"`
	Height int32 `json:"height,omitempty"`
	InitialSyncTime *GithubComSatstreamSsUtilsOrdServerResponsesDuration `json:"initial_sync_time,omitempty"`
	Inscriptions int32 `json:"inscriptions,omitempty"`
	LostSats int32 `json:"lost_sats,omitempty"`
	MinimumRuneForNextBlock string `json:"minimum_rune_for_next_block,omitempty"`
	RuneIndex bool `json:"rune_index,omitempty"`
	Runes int32 `json:"runes,omitempty"`
	SatIndex bool `json:"sat_index,omitempty"`
	Started string `json:"started,omitempty"`
	TransactionIndex bool `json:"transaction_index,omitempty"`
	UnrecoverablyReorged bool `json:"unrecoverably_reorged,omitempty"`
	Uptime *GithubComSatstreamSsUtilsOrdServerResponsesDuration `json:"uptime,omitempty"`
}
