/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package satstream_go_sdk

type GithubComSatstreamSsUtilsBitcoinCliRawTx1 struct {
	Blockhash string `json:"blockhash,omitempty"`
	Blocktime int32 `json:"blocktime,omitempty"`
	Confirmations int32 `json:"confirmations,omitempty"`
	Hash string `json:"hash,omitempty"`
	Hex string `json:"hex,omitempty"`
	Locktime int32 `json:"locktime,omitempty"`
	Size int32 `json:"size,omitempty"`
	Time int32 `json:"time,omitempty"`
	Txid string `json:"txid,omitempty"`
	Version int32 `json:"version,omitempty"`
	Vin []GithubComSatstreamSsUtilsBitcoinCliTxVin1 `json:"vin,omitempty"`
	Vout []GithubComSatstreamSsUtilsBitcoinCliVout `json:"vout,omitempty"`
	Vsize int32 `json:"vsize,omitempty"`
	Weight int32 `json:"weight,omitempty"`
}
