/*
 * Satstream API
 *
 * Satstream API
 *
 * API version: 1.0
 * Contact: team@satstream.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TypesSubscriptionQuota struct {
	// nil means unlimited
	RateLimitMax int32 `json:"rate_limit_max,omitempty"`
	// nil means unlimited
	RateLimitWindowSecs int32 `json:"rate_limit_window_secs,omitempty"`
	TotalRequestQuota int32 `json:"total_request_quota,omitempty"`
}
